sudo: true
services: docker
language: ruby
cache:
- bundler
before_install:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - gem install bundler
install:
- bundle install
rvm:
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake quick
# TODO: come back later and figure out whats wrong with the testing bootrap disabled CI on 2019-03-04
# - bundle exec rake kitchen:ruby-`echo $TRAVIS_RUBY_VERSION | sed -e "s/\.//g"`-debian-8
- gem build sensu-plugins-redis.gemspec
- gem install sensu-plugins-redis-*.gem
before_deploy:
- bash -c "[ ! -d bonsai/ ] && git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai || echo 'bonsai/ exists, skipping git clone'"
deploy:
- provider: rubygems
  api_key:
    secure: Nx//keKnx9rs/hJN9RtQ72iXs+ZRTX4t7vuyOdxDEay8htD3HTMOsFSvwQopzDcArNrsCvIB81M/SXDBTBp7ECsLR2YZAsTYix2Jjt5oKl0ltByGkPGQtqe9q3kSt494Z8CzCi/nuXaYABElF3Dd4bUGa3Q4iQHAnZb3/NyeQiQ=
  gem: sensu-plugins-redis
  on:
    tags: true
    all_branches: true
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-redis
- provider: script
  script: bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh sensu-plugins-redis
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    rvm: 2.4.1

